name: Playwright Tests
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: Preview
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./frontend_web
        run: npm ci
      - name: Install Playwright
        working-directory: ./frontend_web
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./frontend_web
        run: npx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
